//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "n/a"]];
player createDiaryRecord ["Diary", ["Mission", "Your team <marker name = 'start'>start</marker> in city thats under attack."]];
// tasks need to be in reversed order
pmc_objective1 = player createSimpleTask ["Defend city"];
pmc_objective1 setSimpleTaskDescription ["Defend city", "Defend city", "Defend city"];
