//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Finally my squad gets to see some action, its about time. Now lets see how we perform under fire..."]];
player createDiaryRecord ["Diary", ["Mission", "Alpha team <marker name = 'start'>start</marker> from jungle, clear the NVA held <marker name = 'target1'>downtown</marker> objective.<br/><br/>Good luck."]];
// tasks need to be in reversed order
pmc_objective1 = player createSimpleTask ["Clear downtown"];
pmc_objective1 setSimpleTaskDescription ["Clear downtown", "Clear downtown", "Clear downtown"];
