//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Vietnam: The Experience"]];
player createDiaryRecord ["Diary", ["Mission", "USMC <marker name = 'start'>start</marker> in HQ, clear the reqions assigned to you:<br/>
<marker name = 'target1'>Objective 1</marker><br/>
<marker name = 'target2'>Objective 2</marker><br/>
<marker name = 'target3'>Objective 3</marker><br/>
<marker name = 'target4'>Objective 4</marker><br/>
<marker name = 'target5'>Objective 5</marker><br/>
<marker name = 'target6'>Objective 6</marker><br/>
<marker name = 'target7'>Objective 7</marker><br/>
<marker name = 'target8'>Objective 8</marker><br/>
<marker name = 'target9'>Objective 9</marker><br/>
<marker name = 'target10'>Objective 10</marker>"]];
// tasks need to be in reversed order
pmc_objective10 = player createSimpleTask ["Clear the objective 10"];
pmc_objective10 setSimpleTaskDescription ["Clear the objective 10", "Clear the objective 10", "Clear the objective 10"];
pmc_objective9 = player createSimpleTask ["Clear the objective 9"];
pmc_objective9 setSimpleTaskDescription ["Clear the objective 9", "Clear the objective 9", "Clear the objective 9"];
pmc_objective8 = player createSimpleTask ["Clear the objective 8"];
pmc_objective8 setSimpleTaskDescription ["Clear the objective 8", "Clear the objective 8", "Clear the objective 8"];
pmc_objective7 = player createSimpleTask ["Clear the objective 7"];
pmc_objective7 setSimpleTaskDescription ["Clear the objective 7", "Clear the objective 7", "Clear the objective 7"];
pmc_objective6 = player createSimpleTask ["Clear the objective 6"];
pmc_objective6 setSimpleTaskDescription ["Clear the objective 6", "Clear the objective 6", "Clear the objective 6"];
pmc_objective5 = player createSimpleTask ["Clear the objective 5"];
pmc_objective5 setSimpleTaskDescription ["Clear the objective 5", "Clear the objective 5", "Clear the objective 5"];
pmc_objective4 = player createSimpleTask ["Clear the objective 4"];
pmc_objective4 setSimpleTaskDescription ["Clear the objective 4", "Clear the objective 4", "Clear the objective 4"];
pmc_objective3 = player createSimpleTask ["Clear the objective 3"];
pmc_objective3 setSimpleTaskDescription ["Clear the objective 3", "Clear the objective 3", "Clear the objective 3"];
pmc_objective2 = player createSimpleTask ["Clear the objective 2"];
pmc_objective2 setSimpleTaskDescription ["Clear the objective 2", "Clear the objective 2", "Clear the objective 2"];
pmc_objective1 = player createSimpleTask ["Clear the objective 1"];
pmc_objective1 setSimpleTaskDescription ["Clear the objective 1", "Clear the objective 1", "Clear the objective 1"];
