//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", ""]];
player createDiaryRecord ["Diary", ["Mission", "Alpha team <marker name = 'start'>start</marker> from jungle, clear the NVA held <marker name = 'target1'>downtown</marker> objective. Use your air assets to your advantage.<br/><br/>Good luck."]];
// tasks need to be in reversed order
pmc_objective1 = player createSimpleTask ["Clear downtown"];
pmc_objective1 setSimpleTaskDescription ["Clear downtown", "Clear downtown", "Clear downtown"];
