//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Damn VC. I'll blew all them to hell."]];
player createDiaryRecord ["Diary", ["Mission", "Your team <marker name = 'start'>start</marker> in base thats under attack."]];
// tasks need to be in reversed order
pmc_objective1 = player createSimpleTask ["Defend base"];
pmc_objective1 setSimpleTaskDescription ["Defend base", "Defend base", "Defend base"];
